/**
 * Smoke 测试：验证 init 命令能产出可用项目（v0.3 零侵入契约）
 *
 * 运行: node --test tests/smoke.test.mjs
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdirSync, rmSync, existsSync, readFileSync, writeFileSync, cpSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PKG_ROOT = resolve(__dirname, '..');
const BIN = resolve(PKG_ROOT, 'bin/lingshu.mjs');
const TMP = resolve(PKG_ROOT, '.tmp-test');

function runCli(args, opts = {}) {
  return spawnSync(process.execPath, [BIN, ...args], {
    cwd: opts.cwd ?? TMP,
    encoding: 'utf8',
    env: { ...process.env, NO_COLOR: '1' },
  });
}

function freshTmp() {
  if (existsSync(TMP)) rmSync(TMP, { recursive: true, force: true });
  mkdirSync(TMP, { recursive: true });
}

test('CLI 帮助', () => {
  const r = runCli(['--help'], { cwd: PKG_ROOT });
  assert.equal(r.status, 0);
  assert.match(r.stdout, /用法/);
  assert.match(r.stdout, /init/);
  assert.match(r.stdout, /track.*untrack/, '帮助应展示新的 tool 子命令');
});

test('CLI 版本号', () => {
  const r = runCli(['--version'], { cwd: PKG_ROOT });
  assert.equal(r.status, 0);
  assert.match(r.stdout, /^v\d+\.\d+\.\d+/);
});

test('init 创建零侵入项目结构（无 .lingshu / 无 package.json）', () => {
  freshTmp();
  const r = runCli(['init', 'demo-lingshu', '--no-git', '--no-install-hooks']);
  if (r.status !== 0) {
    console.error('STDOUT:', r.stdout);
    console.error('STDERR:', r.stderr);
  }
  assert.equal(r.status, 0, '初始化退出码应为 0');

  const proj = join(TMP, 'demo-lingshu');

  // 应存在的治理资产与基线产物
  for (const p of [
    'reference/rules/lingshu-core.md',
    'reference/rules/ai-behavior.md',
    'CLAUDE.md',
    'AGENTS.md',
    '.gitignore',
    '.github/workflows/rules-consistency.yml',
  ]) {
    assert.ok(existsSync(join(proj, p)), `缺失: ${p}`);
  }

  // 零侵入核心断言：派生仓不应再包含引擎与 package.json
  for (const forbidden of ['.lingshu', 'package.json', '_gitignore']) {
    assert.ok(
      !existsSync(join(proj, forbidden)),
      `零侵入契约：派生仓不应包含 ${forbidden}`,
    );
  }

  // .gitignore 回归（v0.2.5）：不能被 npm 吞掉，且含通配 + personal 忽略
  const gitignore = readFileSync(join(proj, '.gitignore'), 'utf8');
  assert.match(gitignore, /\*-server\//, '.gitignore 应含肢体仓通配');
  assert.match(gitignore, /\*-ui\//, '.gitignore 应含肢体仓通配');
  assert.match(gitignore, /\.cursor\/rules\//, '.gitignore 应忽略 personal 工具产物');

  // 默认不应生成 personal 工具产物（v0.2.3 行为保留）
  for (const personal of [
    '.cursor/rules/lingshu-core.mdc',
    '.trae/rules/lingshu-core.md',
    '.qoder/rules/lingshu-core.md',
    '.agent/rules/lingshu-core.md',
  ]) {
    assert.ok(!existsSync(join(proj, personal)), `默认不应生成 personal 工具产物: ${personal}`);
  }

  // CLAUDE.md：不残留模板名，且头部引用零侵入的 `lingshu sync`
  const claude = readFileSync(join(proj, 'CLAUDE.md'), 'utf8');
  assert.ok(!claude.includes('lingshu-template'), 'CLAUDE.md 不应残留模板名');
  assert.match(claude, /generated by `lingshu sync`/, 'CLAUDE.md 头部应引用 lingshu sync');
  assert.ok(!claude.includes('.lingshu/scripts'), 'CLAUDE.md 不应再引用本地引擎脚本');
});

test('init --all-tools 仍可生成 personal 工具产物', () => {
  freshTmp();
  const r = runCli(['init', 'all-tools-test', '--all-tools', '--no-git', '--no-install-hooks']);
  assert.equal(r.status, 0);

  const proj = join(TMP, 'all-tools-test');
  for (const p of [
    'CLAUDE.md',
    'AGENTS.md',
    '.cursor/rules/lingshu-core.mdc',
    '.trae/rules/lingshu-core.md',
    '.qoder/rules/lingshu-core.md',
    '.agent/rules/lingshu-core.md',
  ]) {
    assert.ok(existsSync(join(proj, p)), `--all-tools 时应生成: ${p}`);
  }
});

test('init --tools 只生成指定工具产物', () => {
  freshTmp();
  const r = runCli([
    'init', 'tools-test',
    '--tools=cursor,claude-code',
    '--no-git', '--no-install-hooks',
  ]);
  assert.equal(r.status, 0);

  const proj = join(TMP, 'tools-test');
  // 指定的工具应生成
  assert.ok(existsSync(join(proj, '.cursor/rules/lingshu-core.mdc')), '应生成 cursor 产物');
  assert.ok(existsSync(join(proj, 'CLAUDE.md')), '应生成 claude-code 产物');
  // 未指定的不应生成
  assert.ok(!existsSync(join(proj, 'AGENTS.md')), '未指定的 codex 不应生成');
  assert.ok(!existsSync(join(proj, '.trae/rules/lingshu-core.md')), '未指定的 trae 不应生成');
});

test('生成的 cursor 产物含规则文件自身的 frontmatter', () => {
  freshTmp();
  runCli(['init', 'fm-test', '--all-tools', '--no-git', '--no-install-hooks']);
  const proj = join(TMP, 'fm-test');
  const mdc = readFileSync(join(proj, '.cursor/rules/lingshu-core.mdc'), 'utf8');
  assert.match(mdc, /^---\n/, 'cursor .mdc 应以 frontmatter 开头');
  assert.match(mdc, /description: 灵枢架构核心准则/, '应含规则文件的 description');
  assert.ok(!mdc.includes('order:'), '保留字段 order 不应输出到产物');
});

test('sync 默认 auto：仅同步 baseline + 已存在产物的 personal', () => {
  freshTmp();
  runCli(['init', 'auto-sync', '--no-git', '--no-install-hooks']);
  const proj = join(TMP, 'auto-sync');

  // 第一次 lingshu sync（auto）→ 不应主动激活 personal 工具
  let r = runCli(['sync'], { cwd: proj });
  assert.equal(r.status, 0);
  for (const personal of ['.cursor/rules/lingshu-core.mdc', '.trae/rules/lingshu-core.md']) {
    assert.ok(!existsSync(join(proj, personal)), `auto 不应主动创建: ${personal}`);
  }

  // 显式 --only=cursor 激活
  r = runCli(['sync', '--only=cursor'], { cwd: proj });
  assert.equal(r.status, 0);
  assert.ok(existsSync(join(proj, '.cursor/rules/lingshu-core.mdc')), '--only=cursor 应生成 cursor 产物');

  // 再次 auto sync：cursor 已存在 → 自动维护，其余仍不激活
  r = runCli(['sync'], { cwd: proj });
  assert.equal(r.status, 0);
  assert.ok(existsSync(join(proj, '.cursor/rules/lingshu-core.mdc')), 'auto 应持续维护已激活工具');
  assert.ok(!existsSync(join(proj, '.trae/rules/lingshu-core.md')), '未激活工具仍不应被动激活');
});

test('sync --all：显式同步所有工具', () => {
  freshTmp();
  runCli(['init', 'all-sync', '--no-git', '--no-install-hooks']);
  const proj = join(TMP, 'all-sync');

  const r = runCli(['sync', '--all'], { cwd: proj });
  assert.equal(r.status, 0);
  for (const p of [
    '.cursor/rules/lingshu-core.mdc',
    '.trae/rules/lingshu-core.md',
    '.qoder/rules/lingshu-core.md',
    '.agent/rules/lingshu-core.md',
  ]) {
    assert.ok(existsSync(join(proj, p)), `--all 时应生成: ${p}`);
  }
});

test('生成项目可独立通过 lingshu sync --check --baseline', () => {
  freshTmp();
  runCli(['init', 'check-proj', '--no-git', '--no-install-hooks']);
  const proj = join(TMP, 'check-proj');

  const r = runCli(['sync', '--check', '--baseline'], { cwd: proj });
  if (r.status !== 0) {
    console.error('CHECK STDOUT:', r.stdout);
    console.error('CHECK STDERR:', r.stderr);
  }
  assert.equal(r.status, 0, '生成项目应通过 sync --check --baseline');
});

test('tool track/untrack 直接编辑 .gitignore', () => {
  freshTmp();
  runCli(['init', 'tool-test', '--no-git', '--no-install-hooks']);
  const proj = join(TMP, 'tool-test');
  const giPath = join(proj, '.gitignore');

  // 初始：cursor 被忽略
  assert.match(readFileSync(giPath, 'utf8'), /^\.cursor\/rules\/$/m, 'fixture：cursor 初始应被忽略');

  // track cursor → 从 .gitignore 移除
  let r = runCli(['tool', 'track', 'cursor'], { cwd: proj });
  assert.equal(r.status, 0);
  assert.ok(
    !/^\.cursor\/rules\/$/m.test(readFileSync(giPath, 'utf8')),
    'track 后 .cursor/rules/ 应从 .gitignore 移除',
  );

  // untrack cursor → 重新追加
  r = runCli(['tool', 'untrack', 'cursor'], { cwd: proj });
  assert.equal(r.status, 0);
  const giFinal = readFileSync(giPath, 'utf8');
  assert.match(giFinal, /^\.cursor\/rules\/$/m, 'untrack 后应重新忽略 .cursor/rules/');
  // 幂等：不应重复追加
  const count = (giFinal.match(/^\.cursor\/rules\/$/gm) || []).length;
  assert.equal(count, 1, 'untrack 应幂等，不重复追加');

  // tool list 应可运行
  r = runCli(['tool', 'list'], { cwd: proj });
  assert.equal(r.status, 0);
  assert.match(r.stdout, /cursor/);
});

test('limb init：创建空肢体目录 + git init', () => {
  freshTmp();
  runCli(['init', 'with-limbs', '--no-git', '--no-install-hooks']);
  const proj = join(TMP, 'with-limbs');

  const r = runCli(['limb', 'init', 'fresh-server'], { cwd: proj });
  assert.equal(r.status, 0);
  assert.ok(existsSync(join(proj, 'fresh-server')), '空肢体目录应已创建');
  assert.ok(existsSync(join(proj, 'fresh-server/.git')), '应在新肢体目录下完成 git init');
});

test('limb 自动维护 .gitignore：约定命名跳过、非约定命名追加', () => {
  freshTmp();
  runCli(['init', 'gi-test', '--no-git', '--no-install-hooks']);
  const proj = join(TMP, 'gi-test');

  const giBefore = readFileSync(join(proj, '.gitignore'), 'utf8');
  assert.match(giBefore, /\*-server\//, 'fixture 校验：模板已含通配');

  // 约定命名：被 *-server/ 通配覆盖，不追加
  let r = runCli(['limb', 'init', 'app-server'], { cwd: proj });
  assert.equal(r.status, 0);
  assert.equal(readFileSync(join(proj, '.gitignore'), 'utf8'), giBefore, '约定命名 .gitignore 不变');

  // 非约定命名：追加一行
  r = runCli(['limb', 'init', 'demo-abc'], { cwd: proj });
  assert.equal(r.status, 0);
  assert.match(readFileSync(join(proj, '.gitignore'), 'utf8'), /^demo-abc\/$/m, '非约定命名应被追加');

  // adopt 幂等
  const outside = join(TMP, 'outside-source');
  mkdirSync(outside);
  r = runCli(['limb', 'adopt', 'demo-xyz', outside], { cwd: proj });
  assert.equal(r.status, 0);
  const giAfterXyz = readFileSync(join(proj, '.gitignore'), 'utf8');
  assert.equal((giAfterXyz.match(/^demo-xyz\/$/gm) || []).length, 1, 'demo-xyz/ 应只追加一次');
});

test('源路径含 node_modules 时模板仍能正确拷贝（回归 v0.2.1 bug）', () => {
  freshTmp();
  const fakeInstall = join(TMP, 'node_modules', '@ruobai', 'lingshu');
  const templateInGlobal = join(fakeInstall, 'templates', 'default');
  cpSync(join(PKG_ROOT, 'templates/default'), templateInGlobal, { recursive: true });
  assert.ok(
    existsSync(join(templateInGlobal, 'reference/rules/lingshu-core.md')),
    'fixture 准备失败：源路径下 reference/rules/ 应存在',
  );

  const r = runCli([
    'init', 'global-install-sim',
    `--template=${templateInGlobal}`,
    '--no-git', '--no-install-hooks',
  ]);
  if (r.status !== 0) {
    console.error('STDOUT:', r.stdout);
    console.error('STDERR:', r.stderr);
  }
  assert.equal(r.status, 0, '源路径含 node_modules 时 init 不应失败');

  const proj = join(TMP, 'global-install-sim');
  assert.ok(
    existsSync(join(proj, 'reference/rules/lingshu-core.md')),
    '回归断言：模板内容必须被拷贝，不可因祖先路径含 node_modules 而过滤',
  );
});

// ===== upgrade（F6）=====

/** 在 dir 下构造一个 v0.2.x 结构的合成项目 */
function buildV02Project(dir) {
  mkdirSync(join(dir, '.lingshu/config'), { recursive: true });
  mkdirSync(join(dir, '.lingshu/scripts'), { recursive: true });
  mkdirSync(join(dir, 'reference/rules'), { recursive: true });
  mkdirSync(join(dir, '.github/workflows'), { recursive: true });

  writeFileSync(join(dir, '.lingshu/config/adapters.mjs'), `
export const sources = [
  { name: 'lingshu-core', path: 'reference/rules/lingshu-core.md' },
  { name: 'ai-behavior', path: 'reference/rules/ai-behavior.md' },
];
export const adapters = {
  cursor: { type: 'directory', target: '.cursor/rules/', extension: '.mdc', frontmatter: {
    'lingshu-core': { name: 'lingshu-core', description: '核心准则', globs: '**/*', trigger: 'always_on' },
    'ai-behavior': { name: 'ai-behavior', description: '行为准则', globs: '**/*', trigger: 'always_on' },
  } },
  'claude-code': { type: 'file', target: 'CLAUDE.md' },
  codex: { type: 'file', target: 'AGENTS.md' },
};
export const baseline = ['claude-code', 'codex'];
`, 'utf8');
  writeFileSync(join(dir, '.lingshu/scripts/sync-rules.mjs'), '// 旧引擎占位\n', 'utf8');
  // 规则文件：无 frontmatter
  writeFileSync(join(dir, 'reference/rules/lingshu-core.md'), '# 核心\n\n正文。\n', 'utf8');
  writeFileSync(join(dir, 'reference/rules/ai-behavior.md'), '# 行为\n\n正文。\n', 'utf8');
  // 脚手架 package.json
  writeFileSync(join(dir, 'package.json'), JSON.stringify({
    name: 'legacy', version: '0.0.0',
    scripts: { sync: 'node .lingshu/scripts/sync-rules.mjs' },
  }, null, 2), 'utf8');
  writeFileSync(join(dir, '.gitignore'), '.cursor/rules/\n.trae/rules/\n', 'utf8');
  writeFileSync(join(dir, '.github/workflows/rules-consistency.yml'),
    'on:\n  push:\n    paths:\n      - \'.lingshu/**\'\nsteps:\n  - run: node .lingshu/scripts/sync-rules.mjs --check --baseline\n',
    'utf8');
}

test('upgrade：v0.2.x → v0.3 机械迁移', () => {
  freshTmp();
  const proj = join(TMP, 'v02-proj');
  buildV02Project(proj);

  const r = runCli(['upgrade'], { cwd: proj });
  if (r.status !== 0) { console.error('STDOUT:', r.stdout); console.error('STDERR:', r.stderr); }
  assert.equal(r.status, 0, 'upgrade 退出码应为 0');

  // .lingshu 与 package.json 应被删除
  assert.ok(!existsSync(join(proj, '.lingshu')), '.lingshu/ 应被删除');
  assert.ok(!existsSync(join(proj, 'package.json')), '纯脚手架 package.json 应被删除');

  // 规则文件应被注入 frontmatter（含原 cursor 的 description）
  const core = readFileSync(join(proj, 'reference/rules/lingshu-core.md'), 'utf8');
  assert.match(core, /^---\r?\norder: 1/, '应注入 order: 1');
  assert.match(core, /description: 核心准则/, '应迁移原 cursor frontmatter 的 description');

  // 基线产物应被重生成
  assert.ok(existsSync(join(proj, 'CLAUDE.md')), '应重生成 CLAUDE.md');
  assert.ok(existsSync(join(proj, 'AGENTS.md')), '应重生成 AGENTS.md');

  // CI 应改为 npx 调用
  const ci = readFileSync(join(proj, '.github/workflows/rules-consistency.yml'), 'utf8');
  assert.match(ci, /npx -y @ruobai\/lingshu sync --check --baseline/, 'CI 应改造为 npx');
  assert.ok(!ci.includes('.lingshu/'), 'CI 不应再引用 .lingshu/');

  // 迁移后应能通过一致性校验
  const check = runCli(['sync', '--check', '--baseline'], { cwd: proj });
  assert.equal(check.status, 0, '迁移后应通过 sync --check --baseline');
});

test('upgrade：已是 v0.3 时幂等（无需迁移）', () => {
  freshTmp();
  runCli(['init', 'already-v3', '--no-git', '--no-install-hooks']);
  const proj = join(TMP, 'already-v3');

  const r = runCli(['upgrade'], { cwd: proj });
  assert.equal(r.status, 0);
  assert.match(r.stdout, /已是 v0\.3|无需迁移/, '应提示无需迁移');
});

test('upgrade：检测 1.0 结构并给出指引（不自动迁移）', () => {
  freshTmp();
  const proj = join(TMP, 'v1-proj');
  mkdirSync(join(proj, '.cursor/rules'), { recursive: true });
  writeFileSync(join(proj, '.cursor/rules/core.mdc'), '# 1.0 规则散落产物\n', 'utf8');

  const r = runCli(['upgrade'], { cwd: proj });
  assert.equal(r.status, 1, '1.0 无法自动迁移，应退出码 1');
  assert.match(r.stdout, /1\.0/, '应说明检测到 1.0 结构');
});

test('upgrade --dry-run：只预览不写盘', () => {
  freshTmp();
  const proj = join(TMP, 'dry-proj');
  buildV02Project(proj);

  const r = runCli(['upgrade', '--dry-run'], { cwd: proj });
  assert.equal(r.status, 0);
  assert.match(r.stdout, /dry-run/);
  // dry-run 不应改动任何文件
  assert.ok(existsSync(join(proj, '.lingshu')), 'dry-run 不应删除 .lingshu');
  assert.ok(existsSync(join(proj, 'package.json')), 'dry-run 不应删除 package.json');
  const core = readFileSync(join(proj, 'reference/rules/lingshu-core.md'), 'utf8');
  assert.ok(!/^---/.test(core), 'dry-run 不应注入 frontmatter');
});

test.after(() => {
  if (existsSync(TMP)) rmSync(TMP, { recursive: true, force: true });
});
