/**
 * 内置 AI 工具适配器注册表（零配置）
 *
 * v0.3 起，adapter 定义内置于 CLI，派生仓不再携带 .lingshu/config/adapters.mjs。
 * 同步引擎从此读本注册表 + 约定发现 reference/rules/*.md，无需任何项目配置文件。
 *
 * 适配器类型：
 *   - 'directory'：每个 source 在目标目录下生成独立文件（Cursor/Trae/Qoder/Antigravity）
 *   - 'file'：所有 source 合并为单一文件（Claude Code 的 CLAUDE.md、Codex 的 AGENTS.md）
 *
 * emitFrontmatter：directory 型适配器是否输出规则文件自身的 frontmatter
 *   （仅 Cursor 的 .mdc 需要；其余 .md 仅输出正文）。
 */

/** 单文件型产物的统一头部（技术中立，不带品牌自称） */
function fileHeader(title) {
  return [
    '<!-- ⚠️ AUTO-GENERATED — DO NOT EDIT -->',
    '<!-- Source: reference/rules/  →  generated by `lingshu sync` -->',
    '<!-- 修改请编辑 reference/rules/ 下的真源文件，然后执行 `lingshu sync` -->',
    '',
    `# ${title}`,
    '',
    '> 本文件由 `lingshu sync` 自动生成，真源位于 `reference/rules/`。',
    '',
  ].join('\n');
}

/** 内置适配器矩阵 */
export const ADAPTERS = {
  cursor: {
    type: 'directory',
    target: '.cursor/rules/',
    extension: '.mdc',
    emitFrontmatter: true,
  },

  trae: {
    type: 'directory',
    target: '.trae/rules/',
    extension: '.md',
  },

  qoder: {
    type: 'directory',
    target: '.qoder/rules/',
    extension: '.md',
  },

  antigravity: {
    type: 'directory',
    target: '.agent/rules/',
    extension: '.md',
  },

  'claude-code': {
    type: 'file',
    target: 'CLAUDE.md',
    header: fileHeader('Claude Code 项目指令'),
    separator: '\n\n---\n\n',
  },

  codex: {
    type: 'file',
    target: 'AGENTS.md',
    header: fileHeader('AI Agents 项目指令'),
    separator: '\n\n---\n\n',
  },
};

/**
 * 默认基线工具（团队产物入库，保证克隆即用）。
 * 注意：项目实际「入库 vs 忽略」以 .gitignore 为准（见 `lingshu tool track/untrack`）；
 * 本常量仅用于 auto 同步时「始终生成」的工具集合的兜底默认。
 */
export const DEFAULT_BASELINE = ['claude-code', 'codex'];
